[package]
name = "wasmflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
rskafka = { path = "../rskafka", features = ["full"] }
webpki-roots = "0.22.0"
rustls = "0.20.4"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1"
