enum status {
    ok,
    error
}

record flow-record {
    key: option<list<u8>>,
    value: option<list<u8>>,
    headers: list<tuple<string, list<u8>>>,
    topic: string,
    partition: s32,
    offset: s64,
    timestamp: s64
}

process-record: function(rec: flow-record) -> status
