sources:
  - !Kafka
      brokers:
        - "my-broker.confluent.cloud:9092"
      topic: my-topic
      group_id: wasmflow-group
      batch_size: 1000000
      sasl:
        !Plain
          username: secret
          password: super-secret
sinks:
  - !S3
      region: us-east-1
      bucket: wasmtime-sink
      key_prefix: my-stream
      file_size: 4096
processors:
  - module_path: "./target/wasm32-wasi/release/wasm_s3_sink.wasm"
